---
title: "Nested experiments"
output: html_notebook
runtime: shiny
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
#library(lme4)
library(nlme)

```

##Parameters of each case

```{r}
inputPanel(
  
  numericInput("mean_A", label = "Mean of case A:",
              value = 1500),
  numericInput("mean_B", label = "Mean of case B:",
              value = 1300)
  
)
```

##Shared parameters

```{r}
inputPanel(
  
  numericInput("n_samples", label = "Number of samples:",
              value = 5,step=1,min=0),
  numericInput("n_measurements", label = "Number of measurements per sample:",
              value = 6,step=1,min=0),
  numericInput("sample_variability", label = "Between-sample variability (standard deviation):",
              value = 500,min=0),
  numericInput("measurement_error", label = "Measurement error (standard deviation):",
              value = 100,min=0)
  
)
```

```{r}

#Simulate data
simulation<-reactive({
  
  set.seed(1)
  
  case<-c(rep("case A",input$n_measurements*input$n_samples),
           rep("case B",input$n_measurements*input$n_samples))
  
  sample<-LETTERS[rep(seq(2*input$n_samples),each=input$n_measurements)]
    
  true_value<-c(rep(input$mean_A,input$n_measurements*input$n_samples),
           rep(input$mean_B,input$n_measurements*input$n_samples))
  
  measurement_error<-rnorm(2*input$n_measurements*input$n_samples,sd=input$measurement_error)
  
  sample_variability<-rep(rnorm(input$n_samples,sd=input$sample_variability),each=input$n_measurements)
  
  data.frame(case,sample,true_value,measurement_error,sample_variability) %>%
    mutate(measured_value=true_value+measurement_error+sample_variability)
  
})

```

##Plot

```{r}

renderPlot({

  plot_data<-simulation()
  
  ggplot(plot_data,aes(x=case,y=measured_value,colour=sample,group=case))+
    stat_summary(fun.data = mean_se, geom = "errorbar")+
    geom_jitter()
    
})

```

##Linear

Here, I feed the means for each sample into the model.

```{r}

renderPrint({
  
  reg_data<-simulation()
  
  reg_data %>%
    group_by(case,sample) %>%
    summarise(measured_value=mean(measured_value)) %>%
    lm(formula=measured_value~case, data=.) %>%
    summary()
  
})

```

##Linear mixed effects
```{r}

renderPrint({
  
  reg_data<-simulation()
  
  reg_data %>%
      lme(measured_value~case,random=~1|sample, data=.) %>%
      summary()
  
})

```

##Raw data

```{r}

renderTable({
  
  simulation()

},digits = 5)
```