---
title: "R Notebook"
output: html_notebook
runtime: shiny
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(broom)

```

#Randomisation
When all parameters including the random seed are kept the same, the simulation results will be the same. This means we can go back to exactly the same simulated data, by remembering the random seed. If we want to re-simulate the data with the rest of the parameters kept constant, the seed can be changed.
```{r}
inputPanel(
  
  numericInput("random_seed", label = "Random seed:",
              value = 1, step = 1)
  
)
```

#Shared parameters

```{r}
inputPanel(
  
  numericInput("n_points", label = "Number of time points:",
              value = 6),
  numericInput("m_points", label = "Number of measurements per time point:",
              value = 3),
  numericInput("sd", label = "Standard deviation of measurements:",
              value = 1)
  
)
```

#Case specific parameters

```{r}
inputPanel(

  numericInput("rate_A", label = "Rate of case A:",
              value = -0.1),
  
  numericInput("intercept_A", label = "Intercept of case A:",
              value = 20)
)

inputPanel(
  numericInput("rate_B", label = "Rate of case B:",
              value = -0.15),
  
  numericInput("intercept_B", label = "Intercept of case B:",
              value = 20)
)


```


```{r}

#Simulate data
simulation<-reactive({
  
  logarithmic<-function(t,rate,intercept){
    return(intercept*(10^(rate*t)))
  }
  
  mn=input$m_points*input$n_points
  
  set.seed(input$random_seed)
  
  
  time_points<-seq(0,input$n_points-1) %>%
    rep(each=input$m_points) 
  
  case<-c(rep("case_A",times=mn),
           rep("case_B",times=mn))
  
  value_A<-logarithmic(time_points,input$rate_A,input$intercept_A)
  
  value_B<-logarithmic(time_points,input$rate_B,input$intercept_B)
  
  error<-rnorm(input$n_points*input$m_points*2,sd=input$sd)

  data.frame(time_points=c(time_points,time_points),
             case=case,
             value=c(value_A,value_B),
             error=error,
             value_error=c(value_A,value_B)+error)
  
})


```

```{r}
renderPlot({
  
  plot_data<-simulation()
  
  #Plot data
  
  ggplot(plot_data,aes(x=time_points,y=value_error,colour=case))+
    stat_summary(fun.y = mean, geom = "line") + 
    stat_summary(fun.data = mean_se, geom = "errorbar")+
    scale_y_log10()
  
})
```

```{r}
renderPlot({
  
  plot_data<-simulation()
  
  #Plot data
  
  ggplot(plot_data,aes(x=time_points,y=value_error,colour=case))+
    geom_smooth()+
    geom_jitter(width = 0.1)+
    scale_y_log10()
  
})
```

```{r}

renderTable({
  
  simulation()

},digits = 5)
```

