---
title: "R Notebook"
output: html_notebook
runtime: shiny
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(broom)

```


```{r}
inputPanel(
  
  numericInput("random_seed", label = "Random seed:",
              value = 1, step = 1),
  
  numericInput("n_points", label = "Number of points in each group:",
              value = 3),
  
  checkboxInput("equal_variances", label="Equal variances:")
  
)

inputPanel(

  numericInput("mean_A", label = "Mean of group A:",
              value = 10),
  
  numericInput("standard_deviation_A", label = "Standard deviation of group A:",
              value = 2)
)

inputPanel(
  numericInput("mean_B", label = "Mean of group B:",
              value = 15),
  
  numericInput("standard_deviation_B", label = "Standard deviation of group B:",
              value = 5)
)


```


```{r}

#Simulate data
simulation<-reactive({
  
  set.seed(input$random_seed)
  
  rbind(
    data.frame(Group="A",Value=rnorm(n = input$n_points,
               mean = input$mean_A,
               sd=input$standard_deviation_A)),
    data.frame(Group="B",Value=rnorm(n = input$n_points,
               mean = input$mean_B,
               sd=input$standard_deviation_B))
    )
  
})


```



```{r}

renderPlot({
  
  plot_data<-simulation()
  
  #Plot data
  
  ggplot(plot_data,aes(x=Group,y=Value,colour=Group))+
    stat_summary(fun.y = mean, geom = "bar") + 
    stat_summary(fun.data = mean_se, geom = "errorbar")+
    geom_jitter(width=0.1)
  
})

renderTable({
  #Run tests
  
  test_data<-simulation()
  
  t.test(Value~Group,data=test_data,var.equal=input$equal_variances) %>% 
    tidy() %>%
    select(estimate_mean_A=estimate1,
           estimate_mean_b=estimate2,
           p.value,
           method,
           alternative)

},digits = 5)
```

